project:
  type: website

website:
  title: "Yannick Winkler"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: about.qmd
        text: About


format:
  html:
    theme: cosmo
    toc: true

execute:
  freeze: auto



