---
title: "Yannick Winkler" 
about:
  template: jolla # trestles , solana, marquee [https://quarto.org/docs/websites/website-about.html]

format:
  html:
    css: style.css  
    template-partials:
      - title-block.html # Use the custom title block partial
    toc: false

title-block-banner: "#00000000"
title-block-banner-color: "rgba(255, 255, 255, 0.9)"
include-in-header:
  - text: |
      <style>
      #title-block-header.quarto-title-block.default .quarto-title-meta {
        color: rgba(255, 255, 255, 0.8);
      }
      
      
      #title-block-header {
        background:
          /* top, transparent black overlay */
          linear-gradient(
            rgba(0, 0, 0, 0.7), 
            rgba(0, 0, 0, 0.7)
          ),
          /* bottom, image */
          url(./img/nn_wanderer.png);
        background-size: cover;
        background-position-y: center;
        height: 250px;   
        opacity: 0.8; 
        z-index: -1; /* Keep behind potential future elements if needed */
      
        /* Ensure the block still takes up space */
        display: block;
        padding: 0;
        margin: 0;
      }
      
      #title-block-header::after {
        content: "";
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background-color: rgba(0, 0, 0, 0.4);
      }
      </style>
---
<!--  ::: {.column-page} -->
<!-- Use column-page for better control over content width on wider screens -->

<b> Welcome! </b>

I am a Research Associate at the Computational Communication Research Group, Department of Communication, Johannes Gutenberg University Mainz. My research focuses on political communication across social media platforms, employing advanced quantitative methods with an emphasis on machine learning techniques and large language models (LLMs).

This website serves as a central place for my academic, professional, and personal activities. If you want to know more about me, head over to the [about page](about.qmd).

------------ <!-- A horizontal rule for separation -->


::: {.grid .custom-grid}
<!-- Using a grid for featured content -->

::: {.g-col-12 .g-col-md-4}
### <i class="bi bi-journal-text"></i> Recent Research <!-- Using Bootstrap icons -->

My latest work explores LLMs for generating experimental stimuli. You can find details on this and other publications here:

[<i class="bi bi-arrow-right-short"></i> View Publications](research.qmd){.btn .btn-sm .btn-outline-primary}
:::


::: {.g-col-12 .g-col-md-4}
### <i class="bi bi-display"></i> Featured Project

I'm currently working on **obsidianchatR**, a way to chat with my obsidian notes.

[<i class="bi bi-github"></i> Project Repository](link-to-project-repo){.btn .btn-sm .btn-outline-secondary}
:::

::: {.g-col-12 .g-col-md-4}
### <i class="bi bi-easel2"></i> Current Teaching

This Sommersemester, I am teaching **Datenanalyse mit R**. The course is designed as an inverted classroom. The course website can be found [here](https://stats.ifp.uni-mainz.de/ba-datenanalyse/).

:::


:::

<!-- ::: -->


